<?php
namespace AppBundle\Entity\Region;

use       AppBundle\Entity\BaseRepository;
use       AppBundle\Service\Api\Region\RegionServiceRepositoryInterface;
use       Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends BaseRepository implements RegionServiceRepositoryInterface
{
}
