<?php
namespace AppBundle\Entity\Region;

use       AppBundle\Entity\BaseRepository;
use       AppBundle\Service\Api\Region\RegionServiceRepositoryInterface;
use       Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends BaseRepository implements RegionServiceRepositoryInterface
{
    /**
     * {@InheritDoc}
     */
    public function findByLocaleName($name, $locale)
    {
        $field = $this->getLocaleField('name', $locale);
        $qb    = $this->createQueryBuilder('r');
        $expr  = $qb->expr();
        
        $qb->where($expr->eq('r.' . $field, ':name'))
           ->setParameters([
               'name' => $name,
           ]);
           
        return $qb->getQuery()->getSingleResult();
    }
}
