services:
    app.api.legacy.price_table:
        class:      AppBundle\Service\Api\Legacy\PriceTable
        arguments: ["@app.http.client.guzzle", "@app.concern.website", "@snc_redis.default"]

    app.api.legacy.starting_price:
        class:      AppBundle\Service\Api\Legacy\StartingPrice
        arguments: ["@app.http.client.guzzle", "@app.concern.website", "@snc_redis.default"]

    app.api.legacy.additional_costs:
        class:      AppBundle\Service\Api\Legacy\AdditionalCosts
        arguments: ["@app.http.client.guzzle", "@app.concern.website", "@snc_redis.default"]

    app.api.legacy.features:
        class:      AppBundle\Service\Api\Legacy\Features
        arguments: ["@app.http.client.guzzle", "@app.concern.website", "@snc_redis.default"]