parameters:
    mailer_from: info@chalet.nl
    mailer_to: abdul.ibrahim16@gmail.com
    app:
        maximum_persons_map:
            1: 8
            2: 12
            3: 12
            4: 16
            5: 18
            6: 20
            7: 22
            8: 24
            9: 26
            10: 28
            11: 30
            12: 32
            13: 36
            14: 38
            15: 40
            16: 50
            17: 50
            18: 50
            19: 50
            20: 50
        optimal_maximum_persons_map:
            1: 4
            2: 6
            3: 6
            4: 8
            5: 9
            6: 10
            7: 11
            8: 12
            9: 13
            10: 14
            11: 15
            12: 16
            13: 18
            14: 19
            15: 20
            16: 25
            17: 25
            18: 28
            19: 28
            20: 50
        reservation_costs: 22.50
        travel_insurance_possible: true
        ten_days_insurance_price_summer: 26.20
        ten_days_insurance_price_default: 36.20
        results_per_page: 50
        default_locale:  nl
        default_website: C
        default_season:  1
        minimalSurveyCount: 1
        deposit_days_after_booking: 10
        total_travel_sum_days_before_arrival: 42
        service:
            api:
                highlight:
                    limit: 6
                    results_per_row: 3
        countries:
            I: 5
            K: 5
        domain:
            local.chalet.nl:
                locale:  nl
                website: C
                season:  1
                country: nl
                name: Chalet.nl
                chat: 2-PTFmcHUgtM
                trustpilot: bd82d1c7@trustpilotservice.com
                ga: UA-2078202-1
                facebook: 156825034385110
                twitter: ChaletNL
                google: +ChaletNlWintersport
                pinterest: chaletNL
                resale: false
                cancel_insurance: 1
                travel_insurance: 1
                damage_insurance: 1
                newsletter: true
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.chalet.nl/api.php"

            local.chalet.eu:
                locale:  en
                website: E
                season:  1
                country: en
                name: Chalet.eu
                chat: false
                trustpilot: 5aa723efa5@trustpilotservice.com
                ga: UA-2078202-6
                facebook: false
                twitter: false
                google: false
                pinterest: false
                resale: true
                cancel_insurance: 1
                travel_insurance: 0
                damage_insurance: 0
                newsletter: false
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.chalet.eu/api.php"

            local.chalettour.nl:
                locale:  nl
                website: T
                season:  1
                country: nl
                name: Chalettour.nl
                chat: false
                trustpilot: false
                ga: UA-2078202-7
                facebook: false
                twitter: false
                google: false
                pinterest: false
                resale: true
                cancel_insurance: 1
                travel_insurance: 1
                damage_insurance: 1
                newsletter: false
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.chalettour.nl/api.php"

            local.chalet.be:
                locale:  nl
                website: B
                season:  1
                country: be
                name: Chalet.be
                chat: 3-eex4-wCgtM
                trustpilot: 959caf69@trustpilotservice.com
                ga: UA-2078202-3
                facebook: false
                twitter: false
                google: false
                pinterest: false
                resale: false
                cancel_insurance: 1
                travel_insurance: 0
                damage_insurance: 1
                newsletter: true
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.chalet.be/api.php"

            local.chaletonline.de:
                locale:  de
                website: D
                season:  1
                country: de
                name: Chaletonline.de
                chat: false
                trustpilot: false
                ga: UA-2078202-20
                facebook: false
                twitter: false
                google: false
                pinterest: false
                resale: false
                cancel_insurance: 1
                travel_insurance: 0
                damage_insurance: 0
                newsletter: false
                newsletter_cancel: false
                legacy_api_uri: "http://legacy.chaletonline.de/api.php"

            local.chaletsinvallandry.nl:
                locale:  nl
                website: V
                season:  1
                country: nl
                name: Chalets in Vallandry
                chat: false
                trustpilot: false
                ga: UA-2078202-10
                facebook: false
                twitter: false
                google: false
                pinterest: false
                resale: true
                cancel_insurance: 1
                travel_insurance: 1
                damage_insurance: 1
                newsletter: false
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.chaletsinvallandry.nl/api.php"

            local.chaletsinvallandry.com:
                locale:  en
                website: Q
                season:  1
                country: en
                name: Chalets in Vallandry
                chat: false
                trustpilot: false
                ga: UA-2078202-9
                facebook: false
                twitter: false
                google: false
                pinterest: false
                resale: true
                cancel_insurance: 1
                travel_insurance: 0
                damage_insurance: 0
                newsletter: false
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.chaletsinvallandry.com/api.php"

            local.venturasol.nl:
                locale:  nl
                website: X
                season:  1
                country: nl
                name: Venturasol Wintersport
                chat: false
                trustpilot: false
                ga: UA-2078202-15
                facebook: 162914327091136
                twitter: Venturasol_nl
                google: false
                pinterest: false
                resale: false
                cancel_insurance: 1
                travel_insurance: 1
                damage_insurance: 1
                newsletter: false
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.venturasol.nl/api.php"

            local.venturasolvacances.nl:
                locale:  nl
                website: Y
                season:  1
                country: nl
                name: Venturasol Vacances
                chat: false
                trustpilot: false
                ga: UA-2078202-16
                facebook: false
                twitter: false
                google: false
                pinterest: false
                resale: true
                cancel_insurance: 1
                travel_insurance: 1
                damage_insurance: 1
                newsletter: false
                newsletter_cancel: false
                company: 2
                legacy_api_uri: "http://legacy.venturasolvacances.nl/api.php"

            local.zomerhuisje.nl:
                locale:  nl
                website: Z
                season:  2
                country: nl
                name: Zomerhuisje.nl
                chat: false
                trustpilot: 47c47023@trustpilotservice.com
                ga: UA-2078202-5
                facebook: 168449903215909
                twitter: Zomerhuisje
                google: false
                pinterest: false
                resale: true
                cancel_insurance: 1
                travel_insurance: 1
                damage_insurance: 1
                newsletter: false
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.zomerhuisje.nl/api.php"

            local.italissima.nl:
                locale:  nl
                website: I
                season:  2
                country: nl
                name: Italissima
                chat: 1-ePbASwCpnf
                trustpilot: b69417c8@trustpilotservice.com
                ga: UA-2078202-11
                facebook: 272671556122756
                twitter: Italissima
                google: false
                pinterest: false
                resale: true
                cancel_insurance: 1
                travel_insurance: 1
                damage_insurance: 1
                newsletter: true
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.italissima.nl/api.php"

            local.italissima.be:
                locale:  nl
                website: K
                season:  2
                country: be
                name: Italissima
                chat: 1-ePbASwCpnf
                trustpilot: eaacc6b4@trustpilotservice.com
                ga: UA-2078202-14
                facebook: false
                twitter: false
                google: false
                pinterest: false
                resale: false
                cancel_insurance: 1
                travel_insurance: 0
                damage_insurance: 1
                newsletter: false
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.italissima.be/api.php"

            local.italyhomes.eu:
                locale:  en
                website: H
                season:  2
                country: en
                name: Italyhomes
                chat: false
                trustpilot: false
                ga: UA-2078202-17
                facebook: false
                twitter: false
                google: false
                pinterest: false
                resale: true
                cancel_insurance: 1
                travel_insurance: 0
                damage_insurance: 0
                newsletter: false
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.italyhomes.eu/api.php"

            local.superski.nl:
                locale:  nl
                website: W
                season:  1
                country: nl
                name: SuperSki
                chat: false
                trustpilot: false
                ga: UA-2078202-13
                facebook: 290286354404681
                twitter: false
                google: false
                pinterest: false
                resale: false
                cancel_insurance: 1
                travel_insurance: 1
                damage_insurance: 1
                newsletter: false
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://legacy.superski.nl/api.php"

            chalet.webtastic.nl:
                locale:  nl
                website: C
                season:  1
                country: nl
                name: Chalet.nl
                chat: 2-PTFmcHUgtM
                trustpilot: bd82d1c7@trustpilotservice.com
                ga: UA-2078202-1
                facebook: 156825034385110
                twitter: ChaletNL
                google: +ChaletNlWintersport
                pinterest: chaletNL
                resale: false
                cancel_insurance: 1
                travel_insurance: 1
                damage_insurance: 1
                newsletter: true
                newsletter_cancel: false
                company: 1
                legacy_api_uri: "http://chalet.webtastic.nl/api.php"

        cancellation_insurances:
            standard:
                id: 1
                active: true
                name: standard
            warranty:
                id: 2
                active: false
                name: warranty
            allrisk:
                id: 3
                active: true
                name: allrisk
            warranty_observation:
                id: 4
                active: false
                name: warranty_observation