parameters:
    mailer_user: abdul.ibrahim16@gmail.com
    mailer_password: ibietje24!
    mailer_to: abdul.ibrahim16@gmail.com
    app:
        travel_insurance_possible: true
        ten_days_insurance_price_summer: 26.20
        ten_days_insurance_price_default: 36.20
        results_per_page: 5
        default_locale:  nl
        default_website: C
        default_season:  1
        minimalSurveyCount: 1
        countries:
            I: 5
            K: 5
        domain:
            local.chalet.nl:
                locale:  nl
                website: C
                season:  1
                country: nl
                name: Chalet.nl

            local.chalet.eu:
                locale:  en
                website: E
                season:  1
                country: en
                name: Chalet.eu

            local.chalettour.nl:
                locale:  nl
                website: T
                season:  1
                country: nl
                name: Chalettour.nl

            local.chalet.be:
                locale:  nl
                website: B
                season:  1
                country: be
                name: Chalet.be

            local.chaletonline.de:
                locale:  de
                website: D
                season:  1
                country: de
                name: Chaletonline.de

            local.chaletsinvallandry.nl:
                locale:  nl
                website: V
                season:  1
                country: nl
                name: Chalets in Vallandry

            local.chaletsinvallandry.com:
                locale:  en
                website: Q
                season:  1
                country: en
                name: Chalets in Vallandry

            local.venturasol.nl:
                locale:  nl
                website: X
                season:  1
                country: nl
                name: Venturasol Wintersport

            local.venturasolvacances.nl:
                locale:  nl
                website: Y
                season:  1
                country: nl
                name: Venturasol Vacances

            local.zomerhuisje.nl:
                locale:  nl
                website: Z
                season:  2
                country: nl
                name: Zomerhuisje.nl

            local.italissima.nl:
                locale:  nl
                website: I
                season:  2
                country: nl
                name: Italissima

            local.italissima.be:
                locale:  nl
                website: K
                season:  2
                country: be
                name: Italissima

            local.italyhomes.eu:
                locale:  en
                website: H
                season:  2
                country: en
                name: Italyhomes

            local.superski.nl:
                locale:  nl
                website: W
                season:  1
                country: nl
                name: SuperSki
        service:
            api:
                highlight:
                    limit: 6