imports:
    - { resource: "../prod/config.yml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/stag/routing.yml"

doctrine_mongodb:
    default_database: chalet_stag

doctrine_mongodb:
    connections:
        default:
            options:
                connect: true
                replicaSet: 'rs1'