imports:
    - { resource: "../prod/config.yml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/stag/routing.yml"

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    write_to:       "%kernel.root_dir%/../web/"
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"

monolog:
    channels: ["controller"]
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        app:
            type:   stream
            path:   "%kernel.logs_dir%/app.log"
            level:  debug
            channels: ["controller"]

doctrine_mongodb:
    default_database: chalet_stag
    connections:
        default:
            server: "%mongodb_server%"
            options:
                connect: true
                replicaSet: 'rs1'