imports:
    - { resource: "../dev/config.yml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/stag/routing.yml"

doctrine_mongodb:
    default_database: chalet_stag

assetic:
    use_controller: true
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"

doctrine_mongodb:
    connections:
        default:
            options:
                replicaSet: 'rs1'