app:
    resource: @AppBundle/Controller/
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error