# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    
    repository:
        abstract:        true
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        
    accommodation.repository:
        class:     AppBundle\Entity\Accommodation\AccommodationRepository
        arguments: [AppBundle\Entity\Accommodation\Accommodation]
        parent:    repository
        
    highlight.repository:
        class:     AppBundle\Entity\Highlight\HighlightRepository
        arguments: [AppBundle\Entity\Highlight\Highlight]
        parent:    repository
        
    type.repository:
        class:     AppBundle\Entity\Type\TypeRepository
        arguments: [AppBundle\Entity\Type\Type]
        parent:    repository
        
    api.accommodation.service:
        class:     AppBundle\Service\Api\Accommodation\AccommodationService
        arguments: ["@accommodation.repository"]
            
    api.highlight.service:
        class:     AppBundle\Service\Api\Highlight\HighlightService
        arguments: ["@highlight.repository"]
            
    api.type.service:
        class:     AppBundle\Service\Api\Type\TypeService
        arguments: ["@type.repository"]