# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: services/listeners.yml }
    - { resource: services/concerns.yml }
    - { resource: services/repositories.yml }
    - { resource: services/api.yml }
    - { resource: services/old.yml }
    - { resource: services/twig.yml }

# Other services
services:

    app.annotations.breadcrumbs:
        class: AppBundle\Annotation\Parser\Breadcrumb
        arguments: [@annotation_reader]

    service.javascript:
        class:      AppBundle\Service\Javascript\JavascriptService
        arguments:  [[]]

    service.utils:
        class: AppBundle\Service\UtilsService
        
    service.filter:
        class: AppBundle\Service\FilterService