# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: services/listeners.yml }
    - { resource: services/concerns.yml }
    - { resource: services/repositories.yml }
    - { resource: services/api/api.yml }
    - { resource: services/api/legacy.yml }
    - { resource: services/twig.yml }
    - { resource: services/app.yml }
    - { resource: services/mailers.yml }
    - { resource: services/security.yml }
    - { resource: services/forms.yml }
    - { resource: services/http.yml }
    - { resource: services/vendors.yml }
    - { resource: services/legacy.yml }