# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    accommodation.repository:
        class:           AppBundle\Entity\Accommodation\AccommodationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:       [AppBundle\Entity\Accommodation\Accommodation]
        
    api.accommodation.service:
            class:     AppBundle\Service\Api\Accommodation\AccommodationService
            arguments: ["@accommodation.repository"]