# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: services/listeners.yml }
    - { resource: services/concerns.yml }
    - { resource: services/repositories.yml }
    - { resource: services/api.yml }
    - { resource: services/old.yml }
    - { resource: services/twig.yml }
    - { resource: services/app.yml }