<?php
namespace AppBundle\Entity\Country;

use       AppBundle\Entity\BaseRepository;
use       AppBundle\Service\Api\Country\CountryServiceRepositoryInterface;
use       Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends BaseRepository implements CountryServiceRepositoryInterface
{
}
