<?php
namespace AppBundle\Entity\Country;

use       AppBundle\Entity\BaseRepository;
use       AppBundle\Service\Api\Country\CountryServiceRepositoryInterface;
use       Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends BaseRepository implements CountryServiceRepositoryInterface
{
    /**
     * {@InheritDoc}
     */
    public function findByLocaleName($name, $locale, $sort = 'alpha')
    {
        switch ($sort) {
                
            case 'slopes':
                $sortField = 'r.totalSlopesDistance';
                $sortOrder = 'DESC';
                break;
                
            case 'altitude':
                $sortField = 'r.maximumAltitude';
                $sortOrder = 'DESC';
                break;
                
            case 'alpha':
            default:
                $sortField = 'r.name';
                $sortOrder = 'ASC';
                break;
        }
        
        $field     = $this->getLocaleField('name', $locale);
        $qb        = $this->createQueryBuilder('c');
        $expr      = $qb->expr();
        
        $qb->select('partial r.{id, name, englishName, germanName, seoName, englishSeoName, germanSeoName, minimumAltitude, maximumAltitude, totalSlopesDistance}, partial c.{id, name, englishName, germanName, title, englishTitle, 
                     germanTitle, startCode, shortDescription, englishShortDescription, germanShortDescription, description, englishDescription, germanDescription, additionalDescription, englishAdditionalDescription, germanAdditionalDescription}, 
                     partial p.{id}')
           ->leftJoin('c.places', 'p')
           ->leftJoin('p.region', 'r')
           ->where($expr->eq('c.' . $field, ':name'))
           ->groupBy('r.id')
           ->orderBy($sortField, $sortOrder)
           ->setParameters([
               'name' => $name,
           ]);
           
        return $qb->getQuery()->getSingleResult();
    }
}
