<?php
namespace AppBundle\Entity\Accommodation;
use       AppBundle\Service\Api\Accommodation\AccommodationServiceRepositoryInterface;
use       Doctrine\ORM\EntityRepository;

/**
 * AccommodationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccommodationRepository extends EntityRepository implements AccommodationServiceRepositoryInterface
{
    /**
     * {@InheritDoc}
     */
    public function all($options = [])
    {
        $criteria = self::getOption($options['where'],  []);
        $order    = self::getOption($options['order'],  null);
        $limit    = self::getOption($options['limit'],  null);
        $offset   = self::getOption($options['offset'], null);
        
        return $this->findBy($criteria, $order, $limit, $offset);
    }
    
    /**
     * {@InheritDoc}
     */
    public function find($by)
    {
        return $this->findOneBy($by);
    }
    
    public static function getOption(&$option, $default = null)
    {
        return isset($option) ? $option : $default;
    }
}
