# App Services
services:

    app.annotations.breadcrumbs:
        class: AppBundle\Annotation\Parser\Breadcrumb
        arguments: [@annotation_reader]

    app.javascript:
        class:      AppBundle\Service\Javascript\JavascriptService
        arguments:  [[]]

    app.utils:
        class: AppBundle\Service\UtilsService

    app.filter:
        class: AppBundle\Service\FilterService

    app.mongo:
        class: AppBundle\Service\Mongo\MongoService
        arguments: [@doctrine_mongodb.odm.default_connection]

    app.monitor:
        class: AppBundle\Service\MonitorService

    app.newsletter:
        class: AppBundle\Service\Newsletter\NewsletterService
        arguments: [@app.concern.website]
