# App Services
services:

    app.annotations.breadcrumbs:
        class: AppBundle\Annotation\Parser\Breadcrumb
        arguments: [@annotation_reader]

    app.javascript:
        class:      AppBundle\Service\Javascript\JavascriptService
        arguments:  [[]]

    app.filter:
        class: AppBundle\Service\FilterService

    app.mongo:
        class: AppBundle\Service\Mongo\MongoService
        arguments: [@doctrine_mongodb.odm.default_connection]

    app.monitor:
        class: AppBundle\Service\MonitorService

    app.newsletter:
        class: AppBundle\Service\Newsletter\NewsletterService
        arguments: [@app.concern.website]

    app.github:
        class: AppBundle\Service\GithubService
        arguments: [@app.security.access.validator.github, @snc_redis.default]
        
    app.file:
        class: AppBundle\Service\File\FileService
        arguments: [@app.mongo, %mongodb_files_database%]

    app.file.file:
        alias: app.file
        
    app.file.accommodation:
        class: AppBundle\Service\File\Accommodation
        arguments: [@app.mongo, %mongodb_files_database%]
        
    app.file.type:
        class: AppBundle\Service\File\Type
        arguments: [@app.mongo, %mongodb_files_database%]
        
    app.file.region:
        class: AppBundle\Service\File\Region
        arguments: [@app.mongo, %mongodb_files_database%]
        
    app.file.place:
        class: AppBundle\Service\File\Place
        arguments: [@app.mongo, %mongodb_files_database%]