# concerns
services:
    app.concern.season:
        class: AppBundle\Concern\SeasonConcern
        arguments: ["%app%"]

    app.concern.website:
        class: AppBundle\Concern\WebsiteConcern
        arguments: ["%app%", "%ssl_enabled"]

    app.concern.locale:
        class: AppBundle\Concern\LocaleConcern
        arguments: [@request_stack]