# Legacy Services
services:
    app.legacy.cmsuser:
        class: AppBundle\Service\Legacy\CmsUser\CmsUserService
        arguments: ["@request_stack", "@app.legacy.cmsuser.repository"]

    app.legacy.cmsuser.repository:
        class: AppBundle\Service\Legacy\CmsUser\Repository
        arguments: ["@doctrine.dbal.default_connection"]