# listeners
services:
    app.listener.breadcrumb:
        class: AppBundle\EventListener\BreadcrumbListener
        arguments: ["@app.annotations.breadcrumbs", "@twig"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 7 }

    app.listener.global_javascript:
        class: AppBundle\EventListener\GlobalJavascriptListener
        arguments: ["@app.javascript"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 8 }

    app.listener.season:
        class: AppBundle\EventListener\SeasonListener
        arguments: ["@app.concern.season"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 9 }

    app.listener.hostname:
        class: AppBundle\EventListener\HostnameListener
        arguments: ["@app.concern.website"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 10 }

    app.listener.locale:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%app%", "@app.concern.locale"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1 }

    app.listener.anonymous:
        class: AppBundle\EventListener\AnonymousListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    app.listener.access:
        class: AppBundle\EventListener\AccessListener
        arguments: ["@=service('app.security.access.handler.' ~ parameter('kernel.environment'))"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.listener.exception:
            class: AppBundle\EventListener\ExceptionListener
            arguments: ["@router", "@app.concern.locale"]
            tags:
                - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }