# listeners
services:
    app.listener.breadcrumb:
        class: AppBundle\EventListener\BreadcrumbListener
        arguments: [@app.annotations.breadcrumbs, @twig]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 1 }

    app.listener.global_javascript:
        class: AppBundle\EventListener\GlobalJavascriptListener
        arguments: [@app.javascript, @app.utils]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 5 }

    app.listener.season:
        class: AppBundle\EventListener\SeasonListener
        arguments: [@app.concern.season]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 10 }

    app.listener.hostname:
        class: AppBundle\EventListener\HostnameListener
        arguments: [@app.concern.website]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 15 }

    app.listener.locale:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%app%"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 32 }

    app.listener.anonymous:
        class: AppBundle\EventListener\AnonymousListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    app.listener.access:
        class: AppBundle\EventListener\AccessListener
        arguments: [%kernel.environment%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }