services:
    old.configuration:
        class: AppBundle\Old\Configuration
        arguments: ["@service_container"]
    
    old.feature:
        class: kenmerken
        calls: 
            - [setConfiguration, [@old.configuration]]
            
    old.rate.table:
        class: tarieventabel
        calls:
            - [setConfiguration, [@old.configuration]]