services:
    old.configuration:
        class: AppBundle\Old\Configuration
        arguments: ["@service_container"]

    old.logger:
        class: AppBundle\Old\Logger

    old.redis:
        class: wt_redis
        arguments: [@old.logger]

    old.redis.wrapper:
        class: AppBundle\Old\RedisWrapper
        arguments: [@service_container]

    old.feature:
        class: kenmerken
        calls:
            - [setConfiguration, [@old.configuration]]

    old.rate.table:
        class: tarieventabel
        calls:
            - [setConfiguration, [@old.configuration]]

    old.rate.table.wrapper:
        class: AppBundle\Old\RateTableWrapper
        arguments: [@service_container]

    old.constants:
        class: AppBundle\Old\Constants
        arguments: [@service_container]

    old.prices:
        class: vanafprijs
        arguments: [@old.redis]
        calls:
            - [setConfiguration, [@old.configuration]]

    old.prices.wrapper:
        class: AppBundle\Old\PricesWrapper
        arguments: [@service_container]