# repositories
services:
    repository.orm:
        abstract:        true
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        calls:
            - [setSeason,  [@app.concern.season]]
            - [setWebsite, [@app.concern.website]]

    repository.odm:
        abstract:        true
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method:  getRepository

    repository.accommodation:
        class:     AppBundle\Entity\Accommodation\AccommodationRepository
        arguments: [AppBundle\Entity\Accommodation\Accommodation]
        parent:    repository.orm

    repository.highlight:
        class:     AppBundle\Entity\Highlight\HighlightRepository
        arguments: [AppBundle\Entity\Highlight\Highlight]
        parent:    repository.orm

    repository.type:
        class:     AppBundle\Entity\Type\TypeRepository
        arguments: [AppBundle\Entity\Type\Type]
        parent:    repository.orm

    repository.place:
        class:     AppBundle\Entity\Place\PlaceRepository
        arguments: [AppBundle\Entity\Place\Place]
        parent:    repository.orm

    repository.region:
        class:     AppBundle\Entity\Region\RegionRepository
        arguments: [AppBundle\Entity\Region\Region]
        parent:    repository.orm

    repository.country:
        class:     AppBundle\Entity\Country\CountryRepository
        arguments: [AppBundle\Entity\Country\Country]
        parent:    repository.orm

    repository.booking:
        class:     AppBundle\Entity\Booking\BookingRepository
        arguments: [AppBundle\Entity\Booking\Booking]
        parent:    repository.orm

    repository.booking.survey:
        class:     AppBundle\Entity\Boooking\Survey\SurveyRepository
        arguments: [AppBundle\Entity\Booking\Survey\Survey]
        parent:    repository.orm

    repository.homepageblock:
        class:     AppBundle\Entity\HomepageBlock\HomepageBlockRepository
        arguments: [AppBundle\Entity\HomepageBlock\HomepageBlock]
        parent:    repository.orm

    repository.file.accommodation:
        class:     AppBundle\Document\File\AccommodationRepository
        arguments: [AppBundle\Document\File\Accommodation]
        parent:    repository.odm

    repository.file.type:
        class:     AppBundle\Document\File\TypeRepository
        arguments: [AppBundle\Document\File\Type]
        parent:    repository.odm

    repository.file.region:
        class:     AppBundle\Document\File\RegionRepository
        arguments: [AppBundle\Document\File\Region]
        parent:    repository.odm

    repository.file.place:
        class:     AppBundle\Document\File\PlaceRepository
        arguments: [AppBundle\Document\File\Place]
        parent:    repository.odm

    repository.file.country:
        class:     AppBundle\Document\File\CountryRepository
        arguments: [AppBundle\Document\File\Country]
        parent:    repository.odm

    repository.user:
        class:     AppBundle\Document\User\UserRepository
        arguments: [AppBundle\Document\User\User]
        parent:    repository.odm