# repositories
services:
    app.repository.orm:
        abstract:        true
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        calls:
            - [setSeason,  ["@app.concern.season"]]
            - [setWebsite, ["@app.concern.website"]]
            - [setLocale,  ["@=service('app.concern.locale').get()"]]
            - [setConfig,  ["%app%"]]

    app.repository.odm:
        abstract:        true
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method:  getRepository

    app.repository.accommodation:
        class:     AppBundle\Entity\Accommodation\AccommodationRepository
        arguments: [AppBundle\Entity\Accommodation\Accommodation]
        parent:    app.repository.orm

    app.repository.highlight:
        class:     AppBundle\Entity\Highlight\HighlightRepository
        arguments: ["@doctrine.dbal.default_connection", "@app.concern.locale", "@app.concern.website", "@app.concern.season"]

    app.repository.type:
        class:     AppBundle\Entity\Type\TypeRepository
        arguments: [AppBundle\Entity\Type\Type]
        parent:    app.repository.orm

    app.repository.place:
        class:     AppBundle\Entity\Place\PlaceRepository
        arguments: [AppBundle\Entity\Place\Place]
        parent:    app.repository.orm

    app.repository.region:
        class:     AppBundle\Entity\Region\RegionRepository
        arguments: [AppBundle\Entity\Region\Region]
        parent:    app.repository.orm

    app.repository.supplier:
        class:     AppBundle\Entity\Supplier\SupplierRepository
        arguments: [AppBundle\Entity\Supplier\Supplier]
        parent:    app.repository.orm

    app.repository.country:
        class:     AppBundle\Entity\Country\CountryRepository
        arguments: [AppBundle\Entity\Country\Country]
        parent:    app.repository.orm

    app.repository.booking:
        class:     AppBundle\Entity\Booking\BookingRepository
        arguments: [AppBundle\Entity\Booking\Booking]
        parent:    app.repository.orm

    app.repository.booking.survey:
        class:     AppBundle\Entity\Boooking\Survey\SurveyRepository
        arguments: [AppBundle\Entity\Booking\Survey\Survey]
        parent:    app.repository.orm
        calls:
            - [setLocale,  ["@=service('app.concern.locale').get()"]]

    app.repository.homepageblock:
        class:     AppBundle\Entity\HomepageBlock\HomepageBlockRepository
        arguments: [AppBundle\Entity\HomepageBlock\HomepageBlock]
        parent:    app.repository.orm

    app.repository.season:
        class:     AppBundle\Entity\Season\SeasonRepository
        arguments: [AppBundle\Entity\Season\Season]
        parent:    app.repository.orm
        calls:
            - [setSeason,  ["@app.concern.season"]]

    app.repository.option:
        class:     AppBundle\Entity\Option\OptionRepository
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setSeason,  ["@app.concern.season"]]
            - [setWebsite, ["@app.concern.website"]]
            - [setLocale,  ["@=service('app.concern.locale').get()"]]

    app.repository.faq:
        class:     AppBundle\Entity\Faq\FaqRepository
        arguments: [AppBundle\Entity\Faq\Faq]
        parent:    app.repository.orm
        calls:
            - [setWebsite, ["@app.concern.website"]]

    app.repository.theme:
        class:     AppBundle\Entity\Theme\ThemeRepository
        arguments: [AppBundle\Entity\Theme\Theme]
        parent:    app.repository.orm
        calls:
            - [setSeason, ["@app.concern.season"]]

    app.repository.price:
        class:     AppBundle\Entity\Price\PriceRepository
        arguments: [AppBundle\Entity\Price\Price]
        parent:    app.repository.orm

    app.repository.file.accommodation:
        class:     AppBundle\Document\File\AccommodationRepository
        arguments: [AppBundle\Document\File\Accommodation]
        parent:    app.repository.odm

    app.repository.file.type:
        class:     AppBundle\Document\File\TypeRepository
        arguments: [AppBundle\Document\File\Type]
        parent:    app.repository.odm

    app.repository.file.region:
        class:     AppBundle\Document\File\RegionRepository
        arguments: [AppBundle\Document\File\Region]
        parent:    app.repository.odm

    app.repository.file.place:
        class:     AppBundle\Document\File\PlaceRepository
        arguments: [AppBundle\Document\File\Place]
        parent:    app.repository.odm

    app.repository.file.country:
        class:     AppBundle\Document\File\CountryRepository
        arguments: [AppBundle\Document\File\Country]
        parent:    app.repository.odm

    app.repository.file.theme:
        class:     AppBundle\Document\File\ThemeRepository
        arguments: [AppBundle\Document\File\Theme]
        parent:    app.repository.odm

    app.repository.general.settings:
        class:     AppBundle\Entity\GeneralSettings\GeneralSettingsRepository
        arguments: [AppBundle\Entity\GeneralSettings\GeneralSettings]
        parent:    app.repository.orm

    app.repository.user:
        class:     AppBundle\Document\User\UserRepository
        arguments: [AppBundle\Document\User\User]
        parent:    app.repository.odm

    app.repository.prices_and_offers.price:
        class:     AppBundle\Service\Api\PricesAndOffers\Repository\PriceRepository
        arguments: ["@doctrine.dbal.default_connection", "@app.concern.website", "@app.concern.season"]

    app.repository.prices_and_offers.offer:
        class:     AppBundle\Service\Api\PricesAndOffers\Repository\OfferRepository
        arguments: ["@doctrine.dbal.default_connection"]

    app.repository.search:
        class:     AppBundle\Service\Api\Search\Repository\Repository
        arguments: ["@doctrine.dbal.default_connection", "@app.concern.locale", "@app.concern.website", "@app.concern.season", "%app%"]

    app.repository.filter_names:
        class:     AppBundle\Service\Api\Search\Repository\FilterNamesRepository
        arguments: ["@doctrine.dbal.default_connection", "@app.concern.locale", "@app.concern.website", "@app.concern.season"]

    app.repository.autocomplete:
        class:     AppBundle\Document\Autocomplete\AutocompleteRepository
        arguments: [AppBundle\Document\Autocomplete\Autocomplete]
        parent:    app.repository.odm
        calls:
            - [setSeason,        ["@app.concern.season"]]
            - [setWebsite,       ["@app.concern.website"]]
            - [setLocale,        ["@service_container"]]
            - [setMongoDatabase, ["%mongodb_database%"]]