# Twig
services:
    twig.extension.app:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container, @router]

    twig.extension.pagination:
        class: AppBundle\Twig\PaginationExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container, @app.concern.locale, @router]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }