# Twig
services:
    app.twig_app_extension:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container, @router]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }