imports:
    - { resource: "../config.yml" }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ["application"]
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        application:
            type:   stream
            path:   "%kernel.logs_dir%/app.log"
            level:  debug
            channels: ["application"]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

doctrine_mongodb:
    default_database: chalet_prod
    connections:
        default:
            server: "%mongodb_server%"
            options:
                connect: true
                replicaSet: 'rs1'